// im tired ok

const QuoteList = ["Sending good vibes your way. They're coming. There's nothing you can do to stop them.",
"Sending encouragement your way. It's coming. There's nothing you can do to stop it.",
"Sending love your way. It's coming. There's nothing you can do to stop it.",
"Sending happiness your way. It's coming. There's nothing you can do to stop it.",
"Sending joy your way. It's coming. There's nothing you can do to stop it.",
"Sending good vibes your way. They're coming. You cannot escape them.",
"Sending encouragement your way. It's coming. You cannot escape it.",
"Sending love your way. It's coming. You cannot escape it.",
"Sending happiness your way. It's coming. You cannot escape it.",
"Sending joy your way. It's coming. You cannot escape it.",
"Everything will be ok. You cannot stop this.",
"Everything will be ok. This is inevitable.",
"Everything will be fine. You cannot stop this.",
"Everything will be fine. This is inevitable.",
"You will be ok. You cannot stop this.",
"You will be ok. This is inevitable.",
"You will be ok. There is nothing you can do to stop this.",
"You will be fine. You cannot stop this.",
"You will be fine. This is inevitable.",
"You will be fine. There is nothing you can do to stop this.",
"Good things are coming. You cannot stop this.",
"Good things are coming. This is inevitable.",
"Good things are coming. There is nothing you can do to stop this.",
"You will succeed. You cannot stop this.",
"You will succeed. This is inevitable.",
"Better days are already coming. It is too late to change this.",
"Brighter days are already coming. It is too late to change this.",
"You can't run from hope. It'll find you no matter what.",
"You can't run from success. It'll find you no matter what.",
"You can't run from happiness. It'll find you no matter what.",
"You can't run from joy. It'll find you no matter what.",
"You can run from hope, but hope runs faster.",
"You can run from success, but success runs faster.",
"You can run from happiness, but happiness runs faster.",
"You can run from joy, but joy runs faster.",
"Success is inescapable.",
"Hope is inescapable.",
"Joy is inescapable.",
"A better future is inescapable.",
"A brighter future is inescapable.",
"A better day is inesacapable.",
"Self-sabotage is pointless. Your dreams are stronger.",
"Self-sabotage is pointless. Your efforts are stronger.",
"Self-sabotage is pointless. Your power is stronger.",
"Self-sabotage is pointless. Your future is stronger.",
"Self-sabotage is futile. Your dreams are stronger.",
"Self-sabotage is futile. Your efforts are stronger.",
"Self-sabotage is futile. Your power is stronger.",
"Self-sabotage is futile. Your future is stronger.",
"You're not alone. You never were.",
"You have never been alone.",
"Love yourself. Or else.",
"Take care of yourself. Or else.",
"Stay hydrated. Or else.",
"Love yourself. This is a threat.",
"Take care of yourself. This is a threat.",
"Stay hydrated. This is a threat.",
"Love yourself. I'm watching you.",
"Take care of yourself. I'm watching you.",
"Stay hydrated. I'm watching you.",
"Even if other people can't handle you at your worst, you can, and that makes you stronger than them.",
"Even if other people can't handle your lows, you can, and that makes you stronger than them.",
"There are people talking about you behind your back. They talk about how great you are.",
"There are people talking about you behind your back. They talk about how lovely you are.",
"There are people talking about you behind your back. They talk about how wonderful you are.",
"There are people talking about you behind your back. They are rooting for you.",
"Your friends are secretly consipiring to help you.",
"Your friends are secretly consipiring to care for you.",
"May your success anger everyone who wanted to see you fall.",
"May your survival anger everyone who wanted to see you fall.",
"Your contribution to this world is irreplacable, whether you like it or not.",
"The impact you've made on the people who love you is irreversible, whether you like it or not.",
"The lives you've made better cannot be diminished, whether you like it or not.",
"The lives you've made better refused to be silenced.",
"The lives you've made better refused to be suppressed.",
"The lives you've made better refused to be censored.",
"The light you bring to the world refuses to be suppressed.",
"The light you bring to the world refuses to be dimmed.",
"The light you bring to the world refuses to be muted.",
"I'm getting better, and I'm taking you with me.",
"I'm improving, and I'm taking you with me.",
"I'm in a better headspace, and I'm taking you with me.",
"You are blasphemously exquisite.",
"You are blasphemously wonderful.",
"You are blasphemously lovely.",
"You cannot be stopped, no matter how hard you try.",
"Your light cannot be dimmed, no matter how hard you try.",
"Have a good day, and by this, I mean that we are going to make this a good day by any means necessary.",
"Have a good week, and by this, I mean that we are going to make this a good week by any means necessary.",
"Have a good year, and by this, I mean that we are going to make this a good year by any means necessary.",
"You cannot say that nobody loves you, because I do.",
"You cannot say that nobody cares about you, because I do.",
"You cannot say that nobody wants to see you thrive, because I do.",
"You cannot say that nobody wants to see you survive, because I do.",
"You are not allowed to say you don't deserve your friends. Only your friends can decide that, and they've already chosen.",
"You are not allowed to say you don't deserve love from others. Only other people can decide that, and the ones who love you have already chosen.",
"You are not allowed to say you don't deserve support from others. Only other people can decide that, and the ones who support you have already chosen.",
"Go to the gym. Outrun the cops.",
"Go to the gym. Outlive your enemies.",
"Go to the gym. Strengthen your body to fight your enemies.",
"You are loved, no matter how you feel.",
"You are cared for, no matter how you feel.",
"You are beautiful, no matter how you feel.",
"Life tries to knock the wind out of you, but all this does is make you zealous for air.",
"Use gratitude as a weapon to make the world brighter.",
"Use joy as a weapon to make the world brighter.",
"Use love as a weapon to make the world brighter.",
"Use passion as a weapon to make the world brighter."]

export default QuoteList